### ISSUE TITLE
华为手机闪退

### ISSUE THREAD

**Issue by lldojso** [uniking/dingding#1]
下次更新能适配下吗？

**Comment by uniking** [comment]
华为什么型号啊,android几啊,是不能用还是能用偶尔闪退?用的是百度网盘里最新的app么?

**Comment by lldojso** [comment]
好几个同事的华为手机都闪退。 最近一个是荣耀V10，安卓9，EMUI9。signed.merge.2019-05-24-10-43-23.com.alibaba.android.rimet_4.6.29_522.apk。打开就闪退。

**Comment by uniking** [comment]
2019-05-24的代码弄乱了，也没测试过。上传了个新的，用vivo iqoo android9测试的，可以试一下。

**Comment by lldojso** [comment]
> 2019-05-24的代码弄乱了，也没测试过。上传了个新的，用vivo iqoo android9测试的，可以试一下。

测试个，可以了，感谢。

**Comment by uniking** [comment]
已适配
