### ISSUE TITLE
版本更新频率

### ISSUE THREAD

**Issue by domnli** [uniking/dingding#3]
一般多久更新一个版本？现在用的4.6.42
另外代码有考虑开源吗？

**Comment by uniking** [comment]
@domnli 我有段时间没用钉钉了，既然您提了，明天上班就做个最新版传上去，以后有大版本更新我会及时上传的。这属于工作的副产品，起初方便自己打卡后来传github让需要的人使用，公司的代码还不能来源呢。

**Comment by domnli** [comment]
@uniking 感谢
